### ISSUE TITLE
Test Clojure

### ISSUE THREAD

**Issue by septyaman** [bepitulaz/BelajarClojure#1]
Clojure test

**Comment by bepitulaz** [comment]
What do you mean? Write about Clojure test, or what?

**Comment by septyaman** [comment]
o orang barat...

**Comment by bepitulaz** [comment]
Iya orang barat, jawa barat. O kamu Indonesia, aku ga liat profil sih. Oke, jadi maksudnya?

**Comment by septyaman** [comment]
just `ping`  ...
